config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :services, path: 'servicos' do
      member do
        put 'like', to: 'services#upvote'
        put 'dislike', to: 'services#downvote'
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'

  get 'state/:id', to: 'states#show', format: 'json'

  get 'area/:area_id/subareas', to: 'application#load_subareas', as: 'subareas', format: :json

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'welcome#index'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_error', via: :all

  post 'reports', to: 'reports#create', as: 'report'
  match 'list/services_with_reports', to: 'lists#services_with_reports', via: :all
  get 'reports/:service_id', to: 'reports#find_reports_by_service', as: 'reports_by_service'
end

app/views/partials/_like_unlike.html.erb
<div data-service="<%= service.id %>" class="row like-dislike likes-container">
    <div class=".col-xs-1">
        <i class="fa <% if user_voted_up_service?(service) %>fa-thumbs-up<%else%>fa-thumbs-o-up<%end%> upvote"></i>
        <span class="number-thumbs-up">(<%= service.get_upvotes.size %>)</span>
    </div>
    <div class=".col-xs-1">
        <i class="fa <% if user_voted_down_service?(service) %>fa-thumbs-down<%else%>fa-thumbs-o-down<%end%>  downvote"></i>
        <span class="number-thumbs-down">(<%= service.get_downvotes.size %>)</span>
    </div>
    <div class=".col-xs-1 report">
      <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#reportModal" onclick="setServiceId(<%= service.id %>);"> 
        Denunciar 
      </button>
    </div>
</div>

app/views/partials/_service.html.erb
<div class="panel panel-default panel-servico">
  <div class="panel-heading">
    <h4 class="panel-title">
      <%= service.name %>
      <div class="pull-right">
        <%= render '/partials/like_unlike', service: service %>
      </div>
    </h4>
  </div>
  <div class="row info">
    <div class="col-sm-5">
      <div class="panel-body description">
        <i class="fa fa-lg fa-info pull-left icon visible-xs"></i>
        <div class="text">
          <%= service.description %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <% unless service.website.blank? %>
          <div class="attr">
            <i class="fa fa-lg fa-external-link text-dark-blue pull-left"></i>
            <div class="service-link"><%= link_to service.website, service.website, target: :_blank %></div>
          </div>
      <% end %>
      <% if !service.phone.blank? %>
        <div class="attr">
          <i class="fa fa-lg fa-phone text-dark-blue pull-left"></i>
          <div><%= service.phone %></div>
        </div>
      <% end %>
      <% if !service.other_phone.blank? %>
        <div class="attr">
          <i class="fa fa-lg fa-phone text-dark-blue pull-left"></i>
          <div><%= service.other_phone %></div>
        </div>
      <% end %>
      <div class="attr">
        <i class="fa fa-lg fa-user text-dark-blue pull-left"></i>
        <div>
          <% if service.owner_name.blank? %>
            <%= service.owner %>
          <% else %>
            <%= service.owner_name %>
            <div class="referer">
              <span>Cadastrado por</span> <%= service.owner %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="attr">
        <i class="fa fa-lg fa-map-marker text-dark-blue pull-left"></i>
        <% if !service.address.street.blank? & !service.address.number.blank? %>
          <div>
            <%= "#{service.address.street}" %>
            <% if !service.address.number.blank? %>
              , <%= "#{service.address.number}"  %>
            <% end %>
          </div>
        <% end %>
        <% if !service.address.complement.blank? %>
          <div>
            <%= "#{service.address.complement}" %>
          </div>
        <% end %>
        <% if !service.address.neighborhood.blank? %>
          <div>
            <%= "#{service.address.neighborhood}" %>
          </div>
        <% end %>
        <div>
          <%= "#{service.address.city.name}, #{service.address.state.name}" %>
        </div>
      </div>
      <% if service.subarea %>
        <div class="attr">
          <i class="fa fa-lg fa-heart text-dark-blue pull-left"></i>
          <div><%= "#{service.subarea.area.area if service.subarea.area}" %></div>
          <div><%= "#{service.subarea.subarea}" %></div>
        </div>
      <% end %>
    </div>
  </div>
  <% if can? :edit, service %>
    <div class="panel-footer text-right">
      <div class="btn-group btn-group-sm">
        <% link_content = "<i class='fa fa-lg fa-pencil'></i>&nbsp;Editar" %>
        <%= link_to link_content.html_safe, edit_service_path(service), class: 'btn btn-default'%>
        <% link_content = "<i class='fa fa-lg fa-times'></i>&nbsp;Excluir" %>
        <%= link_to link_content.html_safe, service_path(service), method: :delete, data: { confirm: "Tem certeza que deseja excluir o serviço?" }, class: 'btn btn-danger'%>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_service_list.html.erb
<div id="posts-<%= params['page'] %>">
  <% @services.each do |service| %>
    <div class="panel panel-default panel-lista">
      <div class="row row-eq-height">
        <div class="col-sm-4 bg-light-blue nome text-dark-blue">
          <div class="row service-name">
            <h2><%= service.name %></h2>
          </div>
          <% if service.subarea %>
            <div class="row service-name">
                <div class=".col-xs-6">
                  <i class="fa fa-heart pull-left"></i>
                </div>
                <div class=".col-xs-6">
                  <%= service.subarea.area.area %>
                </div>
            </div>
            <div class="row service-name">
                <div class=".col-xs-12">
                  <%= service.subarea.subarea %>
                </div>
            </div>
          <% end %>
          <div style="margin-top: 10px;">
            <%= render '/partials/like_unlike', service: service %>
          </div>
        </div>
        <div class="col-sm-8">
          <%= link_to service, class: "btn-go pull-right", "aria-label": "Ver detalhes", title: "Ver detalhes" do %>
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
          <% end %>
          <div class="panel-body info">
            <div class="desc font1-2x">
              <%= service.description %>
            </div>
            <% unless service.website.blank? %>
              <div class="attr">
                <i class="fa fa-lg fa-external-link text-dark-blue pull-left"></i>
                <div class="service-link"><%= link_to service.website.html_safe, service.website, target: :_blank %></div>
              </div>
            <% end %>
            <% if !service.phone.blank? %>
              <div class="attr">
                <i class="fa fa-lg fa-phone text-dark-blue pull-left"></i>
                <div><%= service.phone %></div>
              </div>
            <% end %>
            <div class="attr">
              <i class="fa fa-lg fa-user text-dark-blue pull-left"></i>
              <% if service.owner_name.blank? %>
                <div><%= service.owner %></div>
              <% else %>
                <div><%= service.owner_name %></div>
                <div class="referer">
                  <span>Cadastrado por</span> <%= service.owner %>
              </div>
            <% end %>
            </div>
            <div class="attr">
              <i class="fa fa-lg fa-map-marker text-dark-blue pull-left"></i>
              <div><%= service.address.city.name %> &ndash; <%= service.address.state.name %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div id='infinite-scrolling' style="visibility:hidden; height: 0px;">
    <%= will_paginate @services, renderer: BootstrapPagination::Rails, next_label: 'Seguinte', previous_label: 'Anterior' %>
  </div>
  <%= render '/partials/service_report' %>
</div>
<script>
var setServiceId = function(service_id) {
  $(document).ready(function(){
    $('#report_service_id').val(service_id);
  });
}
</script>

app/views/partials/_service_report.html.erb
<div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :report, url: report_path, :html => {:id => 'report_service_form'}  do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="reportModalLabel">Denunciar este serviço</h4>
      </div>
      <div class="modal-body">
          <%= f.hidden_field :service_id, required: true %>
          <div class="form-group">
            <%= f.label :email, "Insira seu email:", class: "control-label label-required"  %>
            <%= f.text_field(:email, id:'report_email', class: 'form-control') %>
            <span class="error"> </span>
          </div>
          <div class="form-group">
            <%= f.label :detail, "Insira a descrição da sua denúncia para este serviço (máximo 255 caracteres):", class:"control-label label-required" %>
            <%= f.text_area(:detail, id:'description', rows: 10, class: 'form-control', maxlength: "255") %>
            <span class="error"> </span>
          </div>
          <div class="form-group">
            <%= f.check_box :authorize, :id =>"authorize-report" %>
            <%= f.label "Autorizo o envio da denúncia",:for => "authorize-report", class: "control-label label-required" %>
            <span class="error"> </span>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <%= f.submit 'Submeter', class:'btn btn-danger', id:'btn-submit'%>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/partials/_service_with_reports_list.html.erb
<div id="posts-<%= params['page'] %>">
<% @services.each do |service| %>
    <div class="panel panel-default panel-lista">
    <div class="row row-eq-height">
      <div class="col-sm-4 bg-light-blue nome text-dark-blue">
        <h2><%= service.name %></h2>
        <div class="area">
          <i class="fa fa-heart pull-left"></i>
          <div>
            <% if service.subarea %>
              <%= service.subarea.area.area %><br/>
              <%= service.subarea.subarea %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="panel-body info">
          <div class="desc font1-2x">
            <%= service.description %>
          </div>
          <% unless service.website.blank? %>
              <div class="attr">
                <i class="fa fa-lg fa-external-link text-dark-blue pull-left"></i>
                <div class="service-link"><%= link_to service.website.html_safe, service.website, target: :_blank %></div>
              </div>
          <% end %>
          <% if !service.phone.blank? %>
            <div class="attr">
              <i class="fa fa-lg fa-phone text-dark-blue pull-left"></i>
              <div><%= service.phone %></div>
            </div>
          <% end %>
          <div class="attr">
            <i class="fa fa-lg fa-user text-dark-blue pull-left"></i>
            <% if service.owner_name.blank? %>
              <div><%= service.owner %></div>
            <% else %>
              <div><%= service.owner_name %></div>
              <div class="referer">
                <span>Cadastrado por</span> <%= service.owner %>
              </div>
            <% end %>
          </div>
          <div class="attr">
            <i class="fa fa-lg fa-map-marker text-dark-blue pull-left"></i>
            <div><%= service.address.city.name %> &ndash; <%= service.address.state.name %></div>
          </div>
        </div>
      </div>
      <div class="col-sm-2 bg-purple denuncia text-white">
        <span class="title">Denúncias</span>
        <span class="reports"> <%= service.reports_count %> <i class="fa fa-exclamation"></i></span>
        <a class="see-report-detail" href="/reports/<%= service.id %>">Ver denúncias</a>
      </div>
    </div>
  </div>
<% end %>
<div id='infinite-scrolling' style="visibility:hidden; height: 0px;">
  <%= will_paginate @services, renderer: BootstrapPagination::Rails, next_label: 'Seguinte', previous_label: 'Anterior' %>
</div>
</div>